### ISSUE TITLE
Variants and css prop styles do not apply

### ISSUE THREAD

**Issue by 8th713** [modulz/stitches#441]
# Bug report

## Describe the bug

`Div` component variants and css prop styles do not apply.

## To Reproduce

https://codesandbox.io/s/stitches-bug-su9fq?file=/src/App.tsx

## Expected behavior

Variant and css prop styles are applied.

## System information

- Version of Stitches: 0.1.0-canary.12

## Additional context

If multiple stitch components have the same style, the component's base CSS rules will be duplicated and will take precedence over the additional CSS rules.

**Comment by joe-bell** [comment]
Try this approach instead, it should give you the behaviour you're looking for here:

```jsx
const Div = styled('div', {
  margin: 8,
  variants: {
    bg: {
      pink: {
        backgroundColor: 'pink',
      },
      red: {
        backgroundColor: 'red',
      },
      green: {
        backgroundColor: 'green',
      },
    },
  },
  defaultVariants: {
    bg: 'pink'
  }
})
```

**Comment by peduarte** [comment]
Hmm. This most definitely shouldnt be happening.

Looks like we have an issue with the CSS injection of base styles. It gets added twice, and the secon time later in the stylesheet, so it overrides the variants.

Here's the generated CSS
```css
.sxbjjes {
  margin: 8px;
  background-color: pink;
}
.sxbjjesy27ki--bg-red {
  background-color: red;
}
.sxbjjesfqayk--bg-green {
  background-color: green;
}
.sxbjjes2qnvx--css {
  background-color: lime;
}
.sxbjjes {
  margin: 8px;
  background-color: pink;
}
.sxbjjeszz1ir--typography-md {
  font-size: 1.25rem;
}
.sxbjjesibggw--css {
  background-color: skyblue;
}

```
