### ISSUE TITLE
Media queries sorting & grouping

### ISSUE THREAD

**Issue by khusseini** [modulz/stitches#562]
Hello everyone, I have some problems with media queries and breakpoints. I got the following config:
```typescript
import { createCss } from "@stitches/react";

export const { styled, css } = createCss({
  media: {
    xs: '(min-width: 0px)',
    sm: '(min-width: 576px)',
    md: '(min-width: 768px)',
    lg: '(min-width: 992px)',
    xl: '(min-width: 1200px)',
  },
  [...snipped...]
});
```

and the following component
```typescript
import React, { forwardRef, HTMLAttributes } from "react";
import { styled } from "../stitches.config";

const ColUnstyled = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ children, className }, ref) => (
    <div ref={ref} className={className}>
      {children}
    </div>
  )
);

export const Col = styled(ColUnstyled, {
  position: "relative",
  width: "100%",
  paddingRight: "$halfGutter",
  paddingLeft: "$halfGutter",
  flexBasis: 0,
  flexGrow: 1,
  maxWidth: "100%",
  variants: {
    space: {
      1: {
        flex: "0 0 8.333%",
      },
      2: {
        flex: "0 0 16.667%",
      },
      3: {
        flex: "0 0 25%",
      },
      4: {
        flex: "0 0 33.333%",
      },
      5: {
        flex: "0 0 41.667%",
      },
      6: {
        flex: "0 0 50%",
      },
      7: {
        flex: "0 0 58.333%",
      },
      8: {
        flex: "0 0 66.667%",
      },
      9: {
        flex: "0 0 75%",
      },
      10: {
        flex: "0 0 83.333%",
      },
      11: {
        flex: "0 0 91.667%",
      },
      12: {
        flex: "0 0 100%",
      },
    },
  },
});

```

the resulting media queries are as following:
```css
@media (min-width: 576px) {
 .sx5vk7ynsrj8--space-8 {
  flex:0 0 66.667%;
 }
}
@media (min-width: 0px) {
 .sx5vk7y129mk--space-12 {
  flex:0 0 100%;
 }
}
@media (min-width: 576px) {
 .sx5vk7yqwt2t--space-2 {
  flex:0 0 16.667%;
 }
}
```

how can I tell stitches, to 
a) sort the media queries by width 
b) maybe group same media queries?
