### ISSUE TITLE
min/max width fit-content is unable to render

### ISSUE THREAD

**Issue by spice380** [modulz/stitches#655]
# Bug report

## Describe the bug

`min-width: fit-content` and `max-width: fit-content` does not render properly.

## To Reproduce

https://codesandbox.io/s/vigorous-albattani-gkroh?file=/src/App.js

## Expected behavior

The styles listed in autocomplete should be able to used.

## System information

@stitches/react 0.2.2

**Comment by apollonian** [comment]
The declaration properties haven't been hyphen-cased looking at the CSS output for the example you provided.

```css 
--stitches{--:2 c-jjzHqH}@media{.c-jjzHqH{min-width:-moz-fit-content;minWidth:fit-content;max-width:-moz-fit-content;maxWidth:fit-content}}
```

The output is expected as we're passing camel cased names to toSizingValue: https://github.com/modulz/stitches/blob/canary/packages/core/src/convert/toSizingValue.js#L10 and not transforming them further.

As a potential fix may I suggest (would be v. happy to send in a PR if I'm thinking in the correct direction :D):

- [ ] Hyphen casing the names in the declaration string returned by `toSizingValue`.
- [ ] Adding a max-width: fit-content test case to universal-polyfill-prefixed-values.
