### ISSUE TITLE
Multiple of the same variants didn't applied properly on responsive styles

### ISSUE THREAD

**Issue by vasilenka** [modulz/stitches#725]
# Bug report

Previously I've created a discussion in https://github.com/modulz/stitches/discussions/724

## Describe the bug

When 2 or more of the same variants are applied on different responsive styles breakpoints, only the last one is applied properly on the component.

## To Reproduce

I've got this config:
```javascript
// stitch.config.js
export const { styled } = createCss({
  ...
  media: {
    phone: `(min-width: 420px)`,
    tablet: `(min-width: 720px)`,
    desktop: `(min-width: 1024px)`,
    wide: `(min-width: 1536px)`,
  },
  ...
})
```
And then a Flex component that received a justify props and set it according to its variants
```javascript
// Flex.js
const Flex = styled('div', {
  ...,
  variants: {
    justify: {
      start: { justifyContent: "flex-start" },
      center: { justifyContent: "center" },
      end: { justifyContent: "flex-end" },
      between: { justifyContent: "space-between" },
      evenly: { justifyContent: "space-evenly" }
    },
  },
  ...
})

// usage of Flex
return (
  <Flex justify={{ 
        "@initial": "start",
        "@phone": "center",
        "@tablet": "end",
        "@desktop": "between",
        "@wide": "end"
  }}>
   {...items}
  </Flex>
)
```
When I run it, the media query for `@tablet` never applied on the `<Flex />`

You can try this too:
```javascript
justify={{ 
  "@initial": "start",
  "@phone": "center",
  "@tablet": "end",
  "@desktop": "end",
  "@wide": "end"
}}
```
And the `end` variant will only be applied on the `@wide` screen. The tablet `@tablet` and `@desktop` screen still has the `center` variant.

**Here's a sandbox demo:** https://codesandbox.io/s/stitches-responsive-problem-r43lf

## System information

- OS: [macOS]
- Browser: tried on Chrome, Safari TP, and Firefox Nightly
- Version of Stitches: Tried on 0.2.5 and 1.0.0-canary.10

**Comment by peduarte** [comment]
@jonathantneal can you verify? thanks!

**Comment by jonathantneal** [comment]
I’m not certain this is a bug, but is instead a misunderstanding of media queries, and mostly because the old syntax for media queries is not very helpful to authors.

I recommend using the newer media query ranges syntax in your `stitches.config.js`:

```tsx
import { createStitches } from "@stitches/react";

export const { styled } = createStitches({
  media: {
    phone: "(width < 720px)",
    tablet: "(720px <= width < 1024px)",
    desktop: "(1024px <= width < 1536px)",
    wide: "(1536px <= width)",
  },
});
```

With these breakpoints, I verified that the correct styles were applying to the correct breakpoints in the correct order.

https://codesandbox.io/s/stitches-responsive-problem-forked-ghszg?file=/src/stitches.config.js

**Comment by vasilenka** [comment]
Sorry @jonathantneal, I tried your sandbox but it still has not applied correctly
```javascript
<Flex
  justify={{
    '@initial': 'start',
    '@phone': 'center',
    '@tablet': 'end',
    '@desktop': 'between',
    '@wide': 'end',
  }}
>
```
The `@phone` and `@wide` has `end` variant on it, but the applied flex are `start` (which is the `@initial` one)

**Comment by jonathantneal** [comment]
You are right, @vasilenka! I have been investigating this. While I don’t understand why it is happening, it has something to do with `end` being used twice; if that helps you with any work arounds before the fix is in.

**Comment by vasilenka** [comment]
@jonathantneal I made another fork of the sandbox and try to explore the problem, you can find it here: https://codesandbox.io/s/stitches-responsive-problem-forked-nz3ui
https://nz3ui.csb.app/

You may already notice it, but here're what I found:
### Using the old media syntax `(min-width: value)`
<img width="479" alt="Screen Shot 2021-08-18 at 23 02 14" src="https://user-images.githubusercontent.com/7563139/129932163-58eb59d7-c909-4a95-a6fb-74e78bfb4e18.png">

This is the result when viewed on the `@wide` screen (>= 1536px)
The media for `@tablet` appeared here, but no declaration for `@wide` media
It's as if the logic is to take all the same variants that applied to different breakpoints, choose the most relevant rule (in this case `min-width: 720px`), and then applied to the latest/highest breakpoint.

**I added more cases on the sandbox too, you might want to check it yourself to see the behavior. But here're some notes:**
1. Adding `max-value` to the range media syntax like this: `(min-value < width < max-value)` will yield a different result from the old syntax with only `(min-width: min-value)`, even though the expected result is the same because the applied rules should be the same.
2. It's even wilder if you add more duplicated variants. e.g. `start, center, end, end, center` will only apply the `start` value on every breakpoint

I hope this could help you in solving the issue

**Comment by wootsbot** [comment]
@vasilenka @jonathantneal It worked for me by placing `media` at the beginning of everything

```js
import { createStitches } from "@stitches/react";

export const { styled } = createStitches({
  media: {
    phone: "(width < 720px)",
    tablet: "(720px <= width < 1024px)",
    desktop: "(1024px <= width < 1536px)",
    wide: "(1536px <= width)",
  },
...
});
```

**Comment by jonathantneal** [comment]
We haven’t had a chance to look into this much deeper. However, we can see the problem in the final output of the CSS. You will see that the shared key/value pairs under different media queries get mixed together.

```css
--sxs {
	--sxs: 2 c-kZriBw
}

@media {
	 .c-kZriBw {
		display: flex;
		width: 100vw;
		height: 100vh;
	}
}

--sxs {
	--sxs: 3 c-kZriBw-awKDG-justify-start c-kZriBw-ceSYxj-justify-center c-kZriBw-cgrpcB-justify-between c-kZriBw-lfUpcg-justify-end
}

@media {
	 .c-kZriBw-awKDG-justify-start {
		justify-content: flex-start;
	}
	 @media (max-width: 719.9375px) {
		 .c-kZriBw-ceSYxj-justify-center {
			justify-content: center;
		}
		
	}
	 @media (min-width: 1024px) and (max-width: 1535.9375px) {
		 .c-kZriBw-cgrpcB-justify-between {
			justify-content: space-between;
		}
		
	}
	 @media (min-width: 1536px) {
		 @media (min-width: 720px) and (max-width: 1023.9375px) {
			 .c-kZriBw-lfUpcg-justify-end {
				justify-content: flex-end;
			}
			
		}
		
	}
	
}
```
