### ISSUE TITLE
Utils override globalCss selectors

### ISSUE THREAD

**Issue by effectiveduck** [modulz/stitches#788]
# Bug report

## Describe the bug

When i have the following util

```ts
const stitchesConfig = createStitches({
  utils: {
    p: (value: Stitches.PropertyValue<"paddingLeft">) => ({
      paddingTop: value,
      paddingBottom: value,
      paddingLeft: value,
      paddingRight: value,
    }),
  }
}
```

and the following globalCss

```ts
const global = globalCss({
  p: {
    fontSize: "$ms0",
    letterSpacing: "$inter-ms0",
    lineHeight: "$default",
    fontWeight: "$medium",
  },
})
```

the css that gets generated is

```css
paddingTop {
  font-size: var(--fontSizes-ms0);
  letter-spacing: var(--letterSpacings-inter-ms0);
  line-height: var(--lineHeights-default);
  font-weight: var(--fontWeights-medium)
}

paddingBottom {
  font-size: var(--fontSizes-ms0);
  letter-spacing: var(--letterSpacings-inter-ms0);
  line-height: var(--lineHeights-default);
  font-weight: var(--fontWeights-medium)
}

paddingLeft {
  font-size: var(--fontSizes-ms0);
  letter-spacing: var(--letterSpacings-inter-ms0);
  line-height: var(--lineHeights-default);
  font-weight: var(--fontWeights-medium)
}

paddingRight {
  font-size: var(--fontSizes-ms0);
  letter-spacing: var(--letterSpacings-inter-ms0);
  line-height: var(--lineHeights-default);
  font-weight: var(--fontWeights-medium)
}
```

## To Reproduce

Minimal repo: https://codesandbox.io/s/tender-hill-n8srq

## Expected behavior

global style for `p { ... }` is generated

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Stitches: 1.1.0
- Version of Node.js: 16.8.0

Thanks!
