### ISSUE TITLE
maskSize/maskRepeat not working

### ISSUE THREAD

**Issue by benjifx** [modulz/stitches#790]
# Bug report

## Describe the bug

maskSize/maskRepeat rules are not in the output css class

## To Reproduce

I've created a component

```typescript
const Img = styled("div", {
  width: "60px",
  height: "45px",
  background:
    "linear-gradient(90deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%)",
  maskImage: `url(${svg})`,
  maskRepeat: "no-repeat",
  maskSize: "cover"
});
```
The generated output is
```css
.c-imtMFX {
    width: 60px;
    height: 45px;
    background: linear-gradient(
90deg, rgb(131, 58, 180) 0%, rgb(253, 29, 29) 50%, rgb(252, 176, 69) 100%);
    -webkit-mask-image: url(...);
}
```

Here is a sandbox demo https://codesandbox.io/s/stitches-maskimage-masksize-issue-6b9d7

## Expected behavior

`mask-size` and `mask-repeat` should work

## System information

- Version of Stitches: 1.1.0
